sulu_automation.get_fields:
    path: '/fields.{_format}'
    controller: 'sulu_automation.task_controller::cgetFieldsAction'
    methods: GET
    format: json
    requirements:
        _format: json|csv
    options:
        expose: true

sulu_automation.get:
    path: '/{id}.{_format}'
    controller: 'sulu_automation.task_controller::getAction'
    methods: GET
    format: json
    requirements:
        _format: json|csv
    options:
        expose: true

sulu_automation.get_count:
    path: '/count.{_format}'
    methods: GET
    controller: 'sulu_automation.task_controller::getCountAction'
    format: json
    requirements:
        _format: json|csv
    options:
        expose: true

sulu_automation.post:
    path: '/.{_format}'
    controller: 'sulu_automation.task_controller::postAction'
    methods: POST
    format: json
    requirements:
        _format: json|csv
    options:
        expose: true

sulu_automation.put:
    path: '/{id}.{_format}'
    controller: 'sulu_automation.task_controller::putAction'
    methods: PUT
    format: json
    requirements:
        _format: json|csv
    options:
        expose: true

sulu_automation.delete:
    path: '/.{_format}'
    methods: DELETE
    controller: 'sulu_automation.task_controller::cdeleteAction'
    format: json
    requirements:
        _format: json|csv
    options:
        expose: true
