name: Test application

on:
    pull_request:
    push:
        branches:
            - '[0-9]+.x'
            - '[0-9]+.[0-9]+'

jobs:
    test:
        name: 'PHP ${{ matrix.php-version }} (${{ matrix.dependency-versions }})'
        runs-on: ubuntu-latest

        env:
            DATABASE_URL: 'mysql://root:root@127.0.0.1/sulu_automation_test?serverVersion=5.7'

        strategy:
            fail-fast: false
            matrix:
                include:
                    - php-version: '8.2'
                      dependency-versions: 'lowest'

                    - php-version: '8.2'
                      dependency-versions: 'highest'

                    - php-version: '8.3'
                      dependency-versions: 'highest'

                    - php-version: '8.4'
                      dependency-versions: 'highest'
                      composer-options: '--ignore-platform-reqs'

        services:
            mysql:
                image: mysql:5.7
                env:
                    MYSQL_ROOT_PASSWORD: root
                ports:
                    - 3306:3306
                options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=5

        steps:
            - name: Checkout project
              uses: actions/checkout@v2

            - name: Install and configure PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-version }}
                  extensions: 'mysql, gd'
                  tools: 'composer:v2'

            - name: Remove not required tooling
              run: composer remove "*php-cs-fixer*" "*phpstan*" "*rector*" --dev --no-interaction --no-update

            - name: Install composer dependencies
              uses: ramsey/composer-install@v1
              with:
                  dependency-versions: ${{matrix.dependency-versions}}
                  composer-options: ${{ matrix.composer-options }}

            - name: Bootstrap test environment
              run: composer bootstrap-test-environment

            - name: Execute test cases
              run: composer test -- --config ${{ matrix.phpunit-config || 'phpunit.xml.dist' }}

    lint:
        name: 'PHP Lint'
        runs-on: ubuntu-latest

        env:
            DATABASE_URL: 'mysql://root:root@127.0.0.1/sulu_automation_test?serverVersion=5.7'

        services:
            mysql:
                image: mysql:5.7
                env:
                    MYSQL_ROOT_PASSWORD: root
                ports:
                    - 3306:3306
                options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=5

        steps:
            - name: Checkout project
              uses: actions/checkout@v2

            - name: Install and configure PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: 8.3
                  extensions: 'mysql, gd'
                  tools: composer:v2

            - name: Install composer dependencies
              uses: ramsey/composer-install@v1
              with:
                  dependency-versions: highest

            - name: Bootstrap test environment
              run: composer bootstrap-test-environment

            - name: Lint code
              run: composer lint
